name: Update Wakatime Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Fetch the Wakatime Badge and update README as before...

      - name: Trigger Another Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/Bhavyawahie/DSA/actions/workflows/waka-readme.yml/dispatches" \
            -d '{"ref":"main"}'
