name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: bhavyawahie/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: bhavyawahie/DSA
          # content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          CODE_LANG: all_time 
          TIME_RANGE: true
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: master
          TARGET_PATH: readme.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.org
          AUTHOR_NAME: Bhavya Wahie
          AUTHOR_EMAIL: bhavyawahie@gmail.com
          # you can populate email-id with secretes instead